/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-05-18 09:12:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.include;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mainContent_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1682412236797L));
    _jspx_dependants.put("jar:file:/Users/myeongjunpark/javaweb/springwork/springmvc/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/erp/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"/erp/common/css/main.css\" />\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\n");
      out.write("<script\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\n");
      out.write("<script\n");
      out.write("	src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\n");
      out.write("<style>\n");
      out.write("/* Remove the navbar's default margin-bottom and rounded borders */\n");
      out.write(".navbar {\n");
      out.write("	margin-bottom: 0;\n");
      out.write("	border-radius: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("	$(document).ready(function() {\n");
      out.write("		//id가 boardCategory인 엘리먼트의 하위 엘리먼트인 모든 li태그에 동일한 코드를 적용하는 코드\n");
      out.write("		$(\"#boardCategory>li\").each(function(){\n");
      out.write("			//li가 클릭될때마다 alert을 실행 - 현재 작업중인 객체를 의미한다.\n");
      out.write("			$(this).click(function() {\n");
      out.write("				//alert(\"선택됐습니다.\");\n");
      out.write("				category = $(this).text(); //현재 선택한 li의 text추출\n");
      out.write("				//alert(category);\n");
      out.write("				//기존 선택된 li에 대한 active속성을 지우기\n");
      out.write("				$(\"#boardCategory>li\").removeAttr(\"class\");\n");
      out.write("				$(this).attr(\"class\", \"active\"); //현재 선택한 li가 활성화되도록 class속성을 설정\n");
      out.write("				$.ajax({\n");
      out.write("					url : \"/erp/board/ajax/list.do\",\n");
      out.write("					type : \"get\",\n");
      out.write("					data : {\n");
      out.write("						\"category\" : category\n");
      out.write("					},\n");
      out.write("					success : function(data){\n");
      out.write("						//ajax 요청으로 category별 게시판 데이터를 받아옴\n");
      out.write("						//alert(data.length + \"----\" + data[0].id);\n");
      out.write("						//alert(data.write_date);\n");
      out.write("						printdata =\"\";\n");
      out.write("						for(i=0; i<data.length; i++){\n");
      out.write("							//조회된 레코드 갯수만큼 출력할 뷰를 만들기\n");
      out.write("							printdata = printdata + \"<tr><td class='boardContent' style=''>\" \n");
      out.write("									+ \"<a href='/erp/board/read.do?board_no=' + data[i].board_no + '&state=READ'>\"\n");
      out.write("									+ data[i].title + \"</a></td>\" \n");
      out.write("									+ \"<td class='boardDate' style=''>\" + data[i].write_date + \"</td></tr>\"\n");
      out.write("						}\n");
      out.write("						//기존의 데이터를 지우고 노드 추가하기\n");
      out.write("						//alert(printdata);\n");
      out.write("						$(\"#mydatalist\").empty();\n");
      out.write("						$(\"#mydatalist\").append(printdata);\n");
      out.write("					}\n");
      out.write("				});\n");
      out.write("			});\n");
      out.write("		});\n");
      out.write("	\n");
      out.write("	})\n");
      out.write("</script>\n");
      out.write("<title>Insert title here</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<div class=\"container\">\n");
      out.write("		<div class=\"row\">\n");
      out.write("			<div class=\"col-sm-7\">\n");
      out.write("				<div id=\"myCarousel\" class=\"carousel slide\" data-ride=\"carousel\"\n");
      out.write("					style=\"width: 600px; height: 300px\">\n");
      out.write("					<!-- Indicators -->\n");
      out.write("					<ol class=\"carousel-indicators\">\n");
      out.write("						<li data-target=\"#myCarousel\" data-slide-to=\"0\" class=\"active\"></li>\n");
      out.write("						<li data-target=\"#myCarousel\" data-slide-to=\"1\"></li>\n");
      out.write("						<li data-target=\"#myCarousel\" data-slide-to=\"2\"></li>\n");
      out.write("					</ol>\n");
      out.write("\n");
      out.write("					<!-- Wrapper for slides -->\n");
      out.write("					<div class=\"carousel-inner\" role=\"listbox\">\n");
      out.write("						<div class=\"item active\">\n");
      out.write("							<img src=\"/erp/images/multi1.jpg\" alt=\"Image\"\n");
      out.write("								style=\"width: 600px; height: 300px\">\n");
      out.write("\n");
      out.write("						</div>\n");
      out.write("\n");
      out.write("						<div class=\"item\">\n");
      out.write("							<img src=\"/erp/images/multi2.jpg\" alt=\"Image\"\n");
      out.write("								style=\"width: 800px; height: 300px\">\n");
      out.write("\n");
      out.write("						</div>\n");
      out.write("						<div class=\"item\">\n");
      out.write("							<img src=\"/erp/images/multi3.jpg\" alt=\"Image\"\n");
      out.write("								style=\"width: 600px; height: 300px\">\n");
      out.write("\n");
      out.write("						</div>\n");
      out.write("\n");
      out.write("						\n");
      out.write("					</div>\n");
      out.write("\n");
      out.write("					<!-- Left and right controls -->\n");
      out.write("					<a class=\"left carousel-control\" href=\"#myCarousel\" role=\"button\"\n");
      out.write("						data-slide=\"prev\"> <span\n");
      out.write("						class=\"glyphicon glyphicon-chevron-left\" aria-hidden=\"true\"></span>\n");
      out.write("						<span class=\"sr-only\">Previous</span>\n");
      out.write("					</a> <a class=\"right carousel-control\" href=\"#myCarousel\" role=\"button\"\n");
      out.write("						data-slide=\"next\"> <span\n");
      out.write("						class=\"glyphicon glyphicon-chevron-right\" aria-hidden=\"true\"></span>\n");
      out.write("						<span class=\"sr-only\">Next</span>\n");
      out.write("					</a>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"col-sm-5\">\n");
      out.write("				<div class=\"panel panel-primary\"\n");
      out.write("					style=\"border-color: #edeef1; height: 300px; width: 450px\">\n");
      out.write("					<div class=\"panel-footer\">사내소식</div>\n");
      out.write("					<div class=\"panel-body\">\n");
      out.write("						<ul class=\"nav nav-tabs\" id=\"boardCategory\">\n");
      out.write("							<li class=\"active\"><a href=\"#\">게시판</a></li>\n");
      out.write("							<li><a href=\"#\">사내소식</a></li>\n");
      out.write("							<li><a href=\"#\">경조사</a></li>\n");
      out.write("						</ul>\n");
      out.write("						<div id=\"boardMain\" style=\"padding-top: 20px; padding-left: 10px\">\n");
      out.write("							<table id=\"mydatalist\" style=\"overflow: scroll;\">\n");
      out.write("								");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("							</table>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<hr />\n");
      out.write("		<div class=\"row main-row\">\n");
      out.write("			<div class=\"col-sm-3\">\n");
      out.write("				<div class=\"panel panel-primary\"\n");
      out.write("					style=\"border-color: #edeef1; height: 300px\">\n");
      out.write("					<div class=\"panel-footer\">News</div>\n");
      out.write("					<div class=\"panel-body\"></div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"col-sm-3\">\n");
      out.write("				<div class=\"panel panel-primary\"\n");
      out.write("					style=\"border-color: #edeef1; height: 300px\">\n");
      out.write("					<div class=\"panel-footer\">회사소식</div>\n");
      out.write("					<div class=\"panel-body\"></div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"col-sm-3\">\n");
      out.write("				<div class=\"panel panel-primary\"\n");
      out.write("					style=\"border-color: #edeef1; height: 300px\">\n");
      out.write("					<div class=\"panel-footer\">회사소식</div>\n");
      out.write("					<div class=\"panel-body\"></div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"col-sm-3\">\n");
      out.write("				<div class=\"panel panel-primary\"\n");
      out.write("					style=\"border-color: #edeef1; height: 300px\">\n");
      out.write("					<div class=\"panel-footer\">회사소식</div>\n");
      out.write("					<div class=\"panel-body\"></div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/include/mainContent.jsp(128,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("board");
      // /WEB-INF/include/mainContent.jsp(128,8) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/include/mainContent.jsp(128,8) '${boardlist }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${boardlist }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("								<tr>\n");
            out.write("									<td class=\"boardContent\" style=\"\"><a href=\"/erp/board/read.do?board_no=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.board_no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&state=READ\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></td>\n");
            out.write("									<td class=\"boardDate\" style=\"\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.write_date }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("								</tr>\n");
            out.write("								");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
